model:
  type: resnet50
dataset: imagenet
aug: fa_reduced_imagenet
cutout: 0
batch: 1024
epoch: 100
lr: 0.4
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  ema: 0
