model:
  type: wresnet40_2
dataset: cifar100
aug: default
cutout: 16
batch: 128
epoch: 60
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
  ema: 0
